# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:              I ❤️ jank, a tech blag
author:             Arglebargle, aka Scott B.
email:                                          # patched to hide email address behind mailhide
  address:          a..........e@gmail.com      # display address; used as public email  if no token set
  mailhide_token:   Bm5RZ                       # mailhide token
#description: >-                                # `>` fold newlines into spaces; `-` trim trailing newlines
#  YEET to Prod
description: |-                                 # `|` multiline block; `-` trim trailing newlines
  YEET to Prod
baseurl: ""                                     # the subpath of your site, e.g. /blog
url: "https://foundObjects.github.io"           # base hostname & protocol for your site, e.g. http://example.com
show_excerpts:      true                        # index shows post excerpts

# Google Analytics
google_analytics:   UA-115516806-2

# Social media
github_username:    foundObjects
reddit_username:    seaQueue
#twitter_username:  twatter+user

# Build settings
markdown:           kramdown
remote_theme:       "jekyll/minima@v2.5.1"
#remote_theme:      "mmistakes/minimal-mistakes@4.19.1"

# minima skin, this isn't super relevant until minima 3.0 (coming Soon™)
minima:
  skin: classic

plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-include-cache

jekyll-archives:
  enabled:
    - tags

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile               # start of defaults
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/          # end of defaults
  - runprod.sh
